### ISSUE TITLE
Add Specific Audience Displays to Specific OBS Scenes

### ISSUE THREAD

**Issue by Droideka1** [brenapp/tm-switcher#11]
Would be helpful to add this feature. This feature is the same as how we add specific match fields to specific OBS scenes, but with TM Displays. 
The reason I'm wanting this added is I'm removing TM banners from it's program files to have my own graphic animations as backgrounds like how they do it at Vex Dome with their LED screen walls.

**Comment by MayorMonty** [comment]
Do you mean associating specific audience displays with scenes in OBS? This is a good idea! I am not sure how this synergizes with associations by field. 

Would there be a scene in OBS for each combination of Field and Display Type?

**Comment by Droideka1** [comment]
Sorry for late response. Been trying to pitch in a tournament with Admins. 

There could be. Like if you click Skills rankings in TM, OBS would switch to Skills rankings on its separate scene.

**Comment by MayorMonty** [comment]
The current API does not support Audience Display interactions, so closing this for now

**Comment by Droideka1** [comment]
Did you reopen this because of the upcoming TM API?

**Comment by brenapp** [comment]
Yes, with the new API it is now possible to update audience displays. Would love to look into this sort of functionality.

I would assume it would mostly make sense for modes like Alliance Selection, Skills Rankings, Elim Bracket, that sort of thing.

**Comment by brenapp** [comment]
Implemented in #33
