### ISSUE TITLE
Submit Telemetry

### ISSUE THREAD

**Issue by brenapp** [brenapp/tm-switcher#30]
**Is your feature request related to a problem? Please describe.**
In order to aid debugging, it would be helpful if there was an automated way to submit Telemetry data. 

**Describe the solution you'd like**
This should be *opt in*, and anonymous. When the user starts the program, they are asked if they would like to upload the log file so that the developers can see it. The log file is continuously uploaded throughout the lifetime of the program.

**Describe alternatives you've considered**
Getting users to submit the log file themselves

**Additional context**
Obviously any sort of telemetry system is an avenue for creepiness. I want to do this in the most transparent and optional way possible, but even just knowing information like a lot of EPs fail to connect to TM the first time (or fail DWAB auth), would be very helpful for improving workflows.

**Comment by Droideka1** [comment]
I am not an EP, but I do livestream for this one EP. Do I need a token from Dwab in order for your scene switcher to work, or will the program take care of this for me? TM could not bearer token from Dwab server. I am also testing the new scene switcher with a test TM server, and not an official event.
